name: Build APK
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: 3.11 }
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk
        pip install buildozer cython
    - run: |
        buildozer init
        sed -i 's/^title.*/title = DermatAI/' buildozer.spec
        sed -i 's/^package.name.*/package.name = dermatai/' buildozer.spec
        sed -i 's/^requirements.*/requirements = python3,kivy,kivymd,requests,plyer/' buildozer.spec
        buildozer -v android debug
    - uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk

# force trigger
